### PR TITLE
Bugfix/remove existing files

### PR DESCRIPTION
**Pull request by mak001**
Fixes a bug preventing the removal existing images from the dropzone
  - existing files use the file id as the uuid

### CODE REVIEW

**Comment by lozcalver** [comment]
Could you submit the bug fix on its own? I’ll need more time to think about the thumbnails change, potential issues with that are non-image files breaking and providing URLs protected assets

**Comment by mak001** [comment]
sure, should i create a new pr or just remove it from this one?

**Comment by lozcalver** [comment]
If you can update this one and squash the changes into a single commit, that’s fine. Or open a new one if it’s easier 😉

**Comment by mak001** [comment]
i removed the thumbnail generation and squashed everything

**Comment by lozcalver** [comment]
Thank you!

**Pull request merged**
