### PR TITLE
BUGFIX chunked uploads seem to have an undefined response

### LINKED ISSUE #11: BUG chunked uploads seem to have an undefined response
In doing a bit of digging I found that the following only seemed to work for smaller uploads that did not get chunked:
```js
    dropzone.on('success', (file, response) => {
      addHiddenInput(file, response[0]);
    });
```

Updating the logic to the following accesses the response in a different way:
```js
    dropzone.on('success', (file, response) => {
      if (file.upload.chunked) {
        addHiddenInput(file, JSON.parse(file.xhr.response)[0]);
      } else {
        addHiddenInput(file, response[0]);
      }
    });
```

My only thought on why the response in the first case would be undefined is there are multiple requests for the chunk upload. If the js receives the response of any request other than the last one, the response would be empty, causing an issue when trying to add the hidden input.

Admittedly I don't use FE build tools a whole lot so it took a bit to get things compiling to test it. I'm happy to open a PR but I may need some guidance as I did see there was a note in the contributing section of the readme about removing some lines from a the dropzone file before building.

### PR DESCRIPTION
**Pull request by muskie9**
resolves #11

### CODE REVIEW

**Comment by muskie9** [comment]
That totally did the trick. I've updated the PR with the new logic.

**Comment by lozcalver** [comment]
Thanks @muskie9, it looks like the new `bundle.js` isn’t minified, can you run `npm run build` again?

**Comment by muskie9** [comment]
Ah, yes, that's an oversight on my part. I had `watch` running and forgot to run the `build` task. I'll get that updated.

**Comment by muskie9** [comment]
Should be all set now.

**Comment by lozcalver** [comment]
Sweet, thanks @muskie9!

**Pull request merged**
